name: Test pipeline

on: [ push ]

jobs:
  test-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - run: |
          # fix for act to work with setup-python@v2
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r unit-requirements.txt
          pip install -U tools/dbx-0.7.0-py3-none-any.whl
          pip install -e .

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Prepare profile
        run: |
          echo "[dbx-dev-azure]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy integration test
        run: |
          dbx deploy --jobs=cicd_templates_fd0d56ac-sample-integration-test

      - name: Run integration test
        run: |
          dbx launch --job=cicd_templates_fd0d56ac-sample-integration-test --trace



